data:
  dataset_path: "/home/maxime/dataset/car_images"
  batch_size: 64
  image_height: 96
  image_width: 144
  num_workers: 6

model:
  channels: 3
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.01

  architecture: "uvit"
  patch_size: 8
  embed_dim: 480
  depth: 12
  num_heads: 8
  mlp_ratio: 4.0
  vit_dropout: 0.0
  skip_connection_spacing: 1

generation:
  num_images: 16
  num_inference_steps: 1000
  save_dir: "outputs"

training:
  checkpoint_dir: "checkpoints"
  epochs: 600
  learning_rate: 0.0001
  max_grad_norm: 1.0
  save_interval: 4
  use_amp: true
  weight_decay: 0.01
  sample_interval: 2